<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Reservation;
use App\Models\Amenities; // Import the Amenities model
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ReservationController extends Controller
{
    public function create()
    {
        // Fetch cottages and tables from the amenities table
        $cottages = Amenities::where('type', 'cottage')->get();
        $tables = Amenities::where('type', 'table')->get();

        // Pass them to the view
        return view('customer.dashboard', compact('cottages', 'tables'));
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        // Create a new reservation (UUID will be automatically generated by the model)
        $reservation = Reservation::create([
            'customer_id' => auth()->user()->id, // Assuming the user is logged in and is the customer
            'date' => $request->date,
            'startTime' => $request->startTime,
            'endTime' => $request->endTime,
            'cottage_id' => $request->cottage, // Save the selected cottage
            'table_id' => $request->tables,   // Save the selected table
        ]);

        return redirect()->route('customer.dashboard')->with('success', 'Reservation created successfully!');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'date' => 'required|date',
            'startTime' => 'required|date_format:H:i',
            'endTime' => 'required|date_format:H:i',
            'cottage' => 'nullable|exists:amenities,id', 
            'tables' => 'nullable|exists:amenities,id',  
        ]);
    }
}
