<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Reservation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ReservationController extends Controller
{
    public function create()
    {
        return view('customer.dashboard');
    }

    public function store(Request $request)
    {

        $this->validator($request->all())->validate();
        // Create a new reservation (UUID will be automatically generated by the model)
        $reservation = Reservation::create([
            'customer_id' => auth()->user()->id, // Assuming the user is logged in and is the customer
            'date' => $request->date,
            'startTime' => $request->startTime,
            'endTime' => $request->endTime,
        ]);

        // Redirect back or return success message
        return redirect()->route('customer/dashboard')->with('success', 'Reservation created successfully!');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'date' => 'required|date',
            'startTime' => 'required|date_format:H:i',
            'endTime' => 'required|date_format:H:i',
        ]);
    }
}